# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-26 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortenr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortenedurl',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='shortenedurlstat',
            name='viewed_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
