# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-27 04:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortenr', '0002_auto_20171226_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortenedurlstat',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='shortenedurlstat',
            name='latitude',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='shortenedurlstat',
            name='longitude',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
