# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-03 01:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortenr', '0003_auto_20171227_0401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shortenedurlstat',
            name='country',
        ),
        migrations.RemoveField(
            model_name='shortenedurlstat',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='shortenedurlstat',
            name='longitude',
        ),
    ]
